# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Distributor' do
use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
pod 'CocoaAsyncSocket' 
end

target 'DistributorTests' do

end

target 'DistributorUITests' do

end

